// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: proto/atrust.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_HEARTBEAT    FrameType = 0
	FrameType_OPEN_STREAM  FrameType = 1
	FrameType_DATA         FrameType = 2
	FrameType_CLOSE_STREAM FrameType = 3
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "HEARTBEAT",
		1: "OPEN_STREAM",
		2: "DATA",
		3: "CLOSE_STREAM",
	}
	FrameType_value = map[string]int32{
		"HEARTBEAT":    0,
		"OPEN_STREAM":  1,
		"DATA":         2,
		"CLOSE_STREAM": 3,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_atrust_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_proto_atrust_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_proto_atrust_proto_rawDescGZIP(), []int{0}
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "l4"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_proto_atrust_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atrust_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_proto_atrust_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Handshake) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type OpenStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // host:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStream) Reset() {
	*x = OpenStream{}
	mi := &file_proto_atrust_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStream) ProtoMessage() {}

func (x *OpenStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atrust_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStream.ProtoReflect.Descriptor instead.
func (*OpenStream) Descriptor() ([]byte, []int) {
	return file_proto_atrust_proto_rawDescGZIP(), []int{1}
}

func (x *OpenStream) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *OpenStream) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FrameType              `protobuf:"varint,1,opt,name=type,proto3,enum=atrust.FrameType" json:"type,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // for DATA: raw bytes; for OPEN_STREAM: JSON-encoded OpenStream (or protobuf on future)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_atrust_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atrust_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_atrust_proto_rawDescGZIP(), []int{2}
}

func (x *Frame) GetType() FrameType {
	if x != nil {
		return x.Type
	}
	return FrameType_HEARTBEAT
}

func (x *Frame) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_atrust_proto protoreflect.FileDescriptor

const file_proto_atrust_proto_rawDesc = "" +
	"\n" +
	"\x12proto/atrust.proto\x12\x06atrust\"<\n" +
	"\tHandshake\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"A\n" +
	"\n" +
	"OpenStream\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"e\n" +
	"\x05Frame\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.atrust.FrameTypeR\x04type\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*G\n" +
	"\tFrameType\x12\r\n" +
	"\tHEARTBEAT\x10\x00\x12\x0f\n" +
	"\vOPEN_STREAM\x10\x01\x12\b\n" +
	"\x04DATA\x10\x02\x12\x10\n" +
	"\fCLOSE_STREAM\x10\x032;\n" +
	"\rTunnelService\x12*\n" +
	"\x06Tunnel\x12\r.atrust.Frame\x1a\r.atrust.Frame(\x010\x01B#Z!github.com/atrust/poctunnel/protob\x06proto3"

var (
	file_proto_atrust_proto_rawDescOnce sync.Once
	file_proto_atrust_proto_rawDescData []byte
)

func file_proto_atrust_proto_rawDescGZIP() []byte {
	file_proto_atrust_proto_rawDescOnce.Do(func() {
		file_proto_atrust_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atrust_proto_rawDesc), len(file_proto_atrust_proto_rawDesc)))
	})
	return file_proto_atrust_proto_rawDescData
}

var file_proto_atrust_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_atrust_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_atrust_proto_goTypes = []any{
	(FrameType)(0),     // 0: atrust.FrameType
	(*Handshake)(nil),  // 1: atrust.Handshake
	(*OpenStream)(nil), // 2: atrust.OpenStream
	(*Frame)(nil),      // 3: atrust.Frame
}
var file_proto_atrust_proto_depIdxs = []int32{
	0, // 0: atrust.Frame.type:type_name -> atrust.FrameType
	3, // 1: atrust.TunnelService.Tunnel:input_type -> atrust.Frame
	3, // 2: atrust.TunnelService.Tunnel:output_type -> atrust.Frame
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_atrust_proto_init() }
func file_proto_atrust_proto_init() {
	if File_proto_atrust_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atrust_proto_rawDesc), len(file_proto_atrust_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_atrust_proto_goTypes,
		DependencyIndexes: file_proto_atrust_proto_depIdxs,
		EnumInfos:         file_proto_atrust_proto_enumTypes,
		MessageInfos:      file_proto_atrust_proto_msgTypes,
	}.Build()
	File_proto_atrust_proto = out.File
	file_proto_atrust_proto_goTypes = nil
	file_proto_atrust_proto_depIdxs = nil
}
